using System;
using UnityEngine;

/// <summary>Model + placement under a kart's Visual root (front = +Z, ground at y = 0).</summary>
[Serializable]
public class ModelPlacement
{
    public GameObject prefab;
    public Vector3 position;
    public Quaternion rotation = Quaternion.identity;
    public float scale = 1f;
}

/// <summary>A selectable driver in a kart, with modest stat multipliers (1 = baseline feel).</summary>
[Serializable]
public class CharacterDefinition
{
    public string displayName;
    public Color uiColor = Color.white;
    public ModelPlacement kart = new ModelPlacement();
    public ModelPlacement driver = new ModelPlacement();
    public AnimationClip driveClip;
    public Avatar driverAvatar;
    [Range(0.85f, 1.15f)] public float speed = 1f;
    [Range(0.85f, 1.15f)] public float acceleration = 1f;
    [Range(0.85f, 1.15f)] public float handling = 1f;

    /// <summary>1..5 bar value for UI (1.0 = 3 bars).</summary>
    public static int Bars(float multiplier) =>
        Mathf.Clamp(Mathf.RoundToInt(3f + (multiplier - 1f) / 0.03f), 1, 5);
}

/// <summary>All characters available in the lobby (generated by RaceSceneBuilder).</summary>
[CreateAssetMenu(menuName = "Kart/Character Roster")]
public class CharacterRoster : ScriptableObject
{
    public CharacterDefinition[] characters = Array.Empty<CharacterDefinition>();

    public int Count => characters.Length;
    public CharacterDefinition this[int index] => characters[index];

    /// <summary>Replaces the kart's visual with the character and applies its stats.</summary>
    public void ApplyTo(KartController kart, int index)
    {
        Transform visual = kart.Visual;
        for (int i = visual.childCount - 1; i >= 0; i--)
        {
            GameObject child = visual.GetChild(i).gameObject;
            if (child.name == "HeadlightLamp") continue;
            child.SetActive(false);
            if (Application.isPlaying) Destroy(child); else DestroyImmediate(child);
        }
        Spawn(characters[index], visual);
        CharacterDefinition c = characters[index];
        kart.SetStats(c.speed, c.acceleration, c.handling);
    }

    /// <summary>Instantiates kart body + seated driver under a parent. Works in edit and play mode.</summary>
    public static GameObject Spawn(CharacterDefinition c, Transform parent)
    {
        var root = new GameObject("Character_" + c.displayName).transform;
        root.SetParent(parent, false);
        GameObject body = Place(c.kart, root, "KartBody");
        if (body != null) body.AddComponent<KartVisualFx>();
        GameObject driver = Place(c.driver, root, "Driver");
        if (driver != null) driver.AddComponent<DriverRig>().Init(c.driveClip, c.driverAvatar);
        if (Application.isPlaying && ToonStyle.Instance != null) ToonStyle.Instance.Apply(root.gameObject);
        return root.gameObject;
    }

    static GameObject Place(ModelPlacement p, Transform parent, string name)
    {
        if (p == null || p.prefab == null) return null;
        GameObject go = Instantiate(p.prefab, parent, false);
        go.name = name;
        go.transform.localPosition = p.position;
        go.transform.localRotation = p.rotation;
        go.transform.localScale = Vector3.one * p.scale;
        foreach (var col in go.GetComponentsInChildren<Collider>())
        {
            if (Application.isPlaying) Destroy(col); else DestroyImmediate(col);
        }
        return go;
    }
}
