using UnityEngine;

/// <summary>
/// Closed-loop centerline generated by RaceSceneBuilder. Waypoint 0 is the
/// finish line; distances increase in race direction.
/// </summary>
public class RaceTrack : MonoBehaviour
{
    [SerializeField] Vector3[] waypoints;
    [SerializeField] float roadWidth = 10f;

    float[] cumulative;
    float length;

    public float RoadWidth => roadWidth;
    public Vector3[] Waypoints => waypoints;
    public int WaypointCount => waypoints?.Length ?? 0;
    public float Length { get { EnsureCache(); return length; } }

    public void Configure(Vector3[] points, float width)
    {
        waypoints = points;
        roadWidth = width;
        cumulative = null;
    }

    void EnsureCache()
    {
        if (cumulative != null && cumulative.Length == waypoints.Length + 1) return;
        cumulative = new float[waypoints.Length + 1];
        for (int i = 0; i < waypoints.Length; i++)
            cumulative[i + 1] = cumulative[i] + Vector3.Distance(waypoints[i], waypoints[(i + 1) % waypoints.Length]);
        length = cumulative[waypoints.Length];
    }

    /// <summary>Distance along the loop (0..Length) of the closest centerline point.</summary>
    public float Project(Vector3 p)
    {
        EnsureCache();
        float best = float.MaxValue, bestS = 0f;
        int n = waypoints.Length;
        for (int i = 0; i < n; i++)
        {
            Vector3 a = waypoints[i], b = waypoints[(i + 1) % n];
            Vector3 ab = b - a;
            ab.y = 0f;
            Vector3 ap = p - a;
            ap.y = 0f;
            float segLen2 = ab.sqrMagnitude;
            float t = segLen2 > 1e-6f ? Mathf.Clamp01(Vector3.Dot(ap, ab) / segLen2) : 0f;
            float d = (ap - ab * t).sqrMagnitude;
            if (d < best)
            {
                best = d;
                bestS = cumulative[i] + Mathf.Sqrt(segLen2) * t;
            }
        }
        return bestS;
    }

    public Vector3 PointAt(float s)
    {
        Locate(s, out int i, out float t);
        return Vector3.Lerp(waypoints[i], waypoints[(i + 1) % waypoints.Length], t);
    }

    public Vector3 TangentAt(float s)
    {
        Locate(s, out int i, out _);
        Vector3 d = waypoints[(i + 1) % waypoints.Length] - waypoints[i];
        d.y = 0f;
        return d.normalized;
    }

    public Vector3 RightAt(float s) => Vector3.Cross(Vector3.up, TangentAt(s));

    /// <summary>Approximate horizontal turn radius of the centerline at s (large on straights).</summary>
    public float RadiusAt(float s)
    {
        float angle = Vector3.Angle(TangentAt(s - 3f), TangentAt(s + 3f)) * Mathf.Deg2Rad;
        return angle < 0.01f ? 1000f : 6f / angle;
    }

    void Locate(float s, out int index, out float t)
    {
        EnsureCache();
        s = Mathf.Repeat(s, length);
        int lo = 0, hi = waypoints.Length - 1;
        while (lo < hi) // last i with cumulative[i] <= s
        {
            int mid = (lo + hi + 1) / 2;
            if (cumulative[mid] <= s) lo = mid; else hi = mid - 1;
        }
        index = lo;
        float seg = cumulative[lo + 1] - cumulative[lo];
        t = seg > 1e-6f ? (s - cumulative[lo]) / seg : 0f;
    }
}
